/**
 * QR payload format (spec §6.2): `vckc:<token>` and nothing else.
 *
 * The token is the child's `children.qr_token` — 48 lowercase hex characters
 * generated by the database from 24 cryptographically random bytes. No name,
 * phone, birthday or any other personal data is ever encoded.
 */
export const QR_PAYLOAD_PREFIX = "vckc:";

const TOKEN_PATTERN = /^[0-9a-f]{48}$/;

export function buildQrPayload(token: string): string {
  if (!TOKEN_PATTERN.test(token)) throw new Error("Invalid QR token format");
  return `${QR_PAYLOAD_PREFIX}${token}`;
}

/**
 * Extracts the token from a scanned payload, or null when the payload is not
 * a Victory Kids Church QR. Tolerates surrounding whitespace and the
 * uppercase variant some scanners produce, nothing else.
 */
export function parseQrPayload(payload: string): string | null {
  const trimmed = payload.trim();
  if (trimmed.length !== QR_PAYLOAD_PREFIX.length + 48) return null;
  if (trimmed.slice(0, QR_PAYLOAD_PREFIX.length).toLowerCase() !== QR_PAYLOAD_PREFIX) return null;
  const token = trimmed.slice(QR_PAYLOAD_PREFIX.length).toLowerCase();
  return TOKEN_PATTERN.test(token) ? token : null;
}
